services:
  gerald-experience-api:
    container_name: gerald-experience-api
    hostname: gerald-experience-api
    image: gerald-experience-api:latest
    restart: unless-stopped
    build:
      context: .
    ports:
    - 6975:6975
    networks:
      - quickstack-platform-interconnect

networks:
  quickstack-platform-interconnect:
    external: true